
export const REQUEST_SIGNIN_PENDING = 'REQUEST_SIGNIN_PENDING';
export const REQUEST_SIGNIN_SUCCESS = 'REQUEST_SIGNIN_SUCCESS';
export const REQUEST_SIGNIN_FAILED = 'REQUEST_SIGNIN_FAILED';
export const QUICK_TECHNIQUE_PAGE = 'QUICK_TECHNIQUE_PAGE';
export const TECHNIQUE_PAGE = 'TECHNIQUE_PAGE';



