
export const REQUEST_SIGNIN_PENDING = 'REQUEST_SIGNIN_PENDING';
export const REQUEST_SIGNIN_SUCCESS = 'REQUEST_SIGNIN_SUCCESS';
export const REQUEST_SIGNIN_FAILED = 'REQUEST_SIGNIN_FAILED';
export const QUICK_TECHNIQUE_PAGE = 'QUICK_TECHNIQUE_PAGE';
export const WEEKLY_TECHNIQUE_PAGE = 'WEEKLY_TECHNIQUE_PAGE';
export const EMAIL_CHANGE = 'EMAIL_CHANGE';
export const PASSWORD_CHANGE = 'PASSWORD_CHANGE';
export const GI_TECH = 'GI_TECH';
export const NO_GI_TECH = 'NO_GI_TECH';
export const DRILLS = 'DRILLS';
export const SYLLIBUS = 'SYLLIBUS';



